# PD控制参数
kp_params:
  leg0: [100.0, 70.0, 70.0]
  leg1: [100.0, 70.0, 70.0]
  leg2: [100.0, 70.0, 70.0]
  leg3: [100.0, 70.0, 70.0]

# PD控制参数
kd_params:
  leg0: [0.5, 0.5, 0.5]
  leg1: [0.5, 0.5, 0.5]
  leg2: [0.5, 0.5, 0.5]
  leg3: [0.5, 0.5, 0.5]

# 目标足端位置 (相对于hip坐标系, 单位: 米)
target_foot_pos_params:
  leg0: [  0.0, -0.10, -0.30]
  leg1: [  0.0,  0.10, -0.30]
  leg2: [  0.0, -0.10, -0.30]
  leg3: [  0.0,  0.10, -0.30]

# 相位参数
phase_values: [1.0, 1.0, 1.0, 1.0]
